### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by tyru** [tyru/notify-changed.vim#4]

**Comment by tyru** [comment]
<img width="382" alt="スクリーンショット 2020-04-10 9 37 36" src="https://user-images.githubusercontent.com/48169/78953099-aa98f480-7b12-11ea-8ada-95260247cf77.png">

**Comment by tyru** [comment]
![image](https://user-images.githubusercontent.com/48169/78960371-d3c47f80-7b28-11ea-8b44-3d1695a588df.png)

**Comment by tyru** [comment]
![image](https://user-images.githubusercontent.com/48169/78960964-aaa4ee80-7b2a-11ea-87c8-dc6cc38d9914.png)

**Comment by tyru** [comment]
![ss](https://user-images.githubusercontent.com/48169/78962052-61569e00-7b2e-11ea-813c-2a3a26b8949e.png)

**Comment by kuuote** [comment]
![ss](https://user-images.githubusercontent.com/36663503/78963087-505b5c00-7b31-11ea-9af5-bece48b912f4.png)
